import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/utilies/Provider";
// In layout.tsx (if using App Router)
import 'leaflet/dist/leaflet.css';
import { Toaster } from 'react-hot-toast';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Providers>
        {children}
        <Toaster position="top-right" toastOptions={{ duration: 4000 }} />
      </Providers>
      </body>
    </html>
  );
}
